### ISSUE TITLE
Set up a simple contract on Goerli for testing JSON implementations

### ISSUE THREAD

**Issue by bitbeckers** [Network-Goods/hypercerts-sdk#18]
We'll set up a simple contract on Goerli for testing JSON implementations

_Originally posted by @bitbeckers in https://github.com/Network-Goods/hypercerts/issues/98#issuecomment-1380762061_

**Comment by ccerv1** [comment]
FYI, here's a uri for testing: ipfs://bafkreicevmmp5yg73r6myejkufqbtr5xppp2dxli4lfqywarf2jotqoxkm/

**Comment by bitbeckers** [comment]
Contract deployed and tested with your URI on Goerli:
[Etherscan](https://goerli.etherscan.io/address/0xffb1fbff7a40ea441aeae8036812af116f593995)
[First mint](https://goerli.etherscan.io/tx/0x1abbe4e869ed2e9fb6c464834b247337ff7e34025ee200cfbaa4c8a70d831ede)
[OpenSea](https://testnets.opensea.io/assets/goerli/0xffb1fbff7a40ea441aeae8036812af116f593995/1)

This contract is just a simple minter where you pass the URI. So no bells and whistles

**Comment by bitbeckers** [comment]
The first thing I notice is that only the `attributes` are parsed instead of both `attributes` and `properties`. Maybe try with everything under `properties`?
